### PR TITLE
libhybris: Bump to latest from upstream

### PR DESCRIPTION
**Pull request by Herrie82**
Bump SRCREV to latest from upstream, issues with Tenderloin seem solved there as well.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Herrie82** [comment]
@shr-project Needs https://github.com/webOS-ports/meta-webos-ports/pull/441 to be merged at the same time

**Comment by Tofee** [comment]
lgtm

**Comment by Tofee** [comment]
I'm fine with that last version

**Comment by shr-project** [comment]
Merged thanks!
c1f92fe8..243e825d dunfell -> dunfell
c1f92fe8..243e825d master -> master
4d88a09e..8e772bf9 zeus -> zeus

**Pull request closed without merging**
