### PR TITLE
android-headers.inc: Make it work with Android 11.0 headers

### PR DESCRIPTION
**Pull request by Herrie82**
Android 11 provides a android-headers.pc.in instead of a android-headers.in file. Make it work in both cases.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by JamiKettunen** [comment]
This would break the pkg-config here as far as I can tell, [the file](https://github.com/Halium/android-headers/blob/1e0ef4a454760b5cbcd04733b34372f0b7c4c194/android-headers.pc.in) cannot be copied as-is due to the template `@includedir@` which is [replaced with a sed during `make install`](https://github.com/Halium/android-headers/blob/1e0ef4a454760b5cbcd04733b34372f0b7c4c194/Makefile#L12).

Is there any particular reason the Makefile cannot be invoked directly in here? Can the upstream Makefiles be patched so that they work here as well as for other distribution packages, or would extra fixups still have to be done here (and how)?

**Comment by Herrie82** [comment]
> This would break the pkg-config here as far as I can tell, [the file](https://github.com/Halium/android-headers/blob/1e0ef4a454760b5cbcd04733b34372f0b7c4c194/android-headers.pc.in) cannot simply be copied and used as-is due to the template `@includedir@` which is [replaced with a sed during `make install`](https://github.com/Halium/android-headers/blob/1e0ef4a454760b5cbcd04733b34372f0b7c4c194/Makefile#L12).
> 
> Is there any particular reason the Makefile cannot be invoked directly in here? Can the upstream Makefiles be patched so that they work here as well as for other distribution packages, or would extra fixups still have to be done here (and how)?

Really not sure why the Makefile is not being used here, to be honest.... I would need to get my Halium 11.0 image to build and to do a full test to see if things work or not

**Comment by Herrie82** [comment]
It seems the original recipe dates back to UBTouch 4.4/5.1 Android days, it could be things improved a lot since then, just we never bothered to check the Makefiles with newer Android versions I guess. It might be something to check and see if we could fix those instead. For now our targets still use Halium 9.0, so pushing this as intermediary and reverting the android-headers so it works for you should be fine.

**Comment by Herrie82** [comment]
@shr-project This seems to be more correct now.

**Comment by Herrie82** [comment]
@shr-project I build tested this with an Android 11 target and confirm it's working correctly now. Please pick to scarthgap etc as well.

**Pull request merged**
