### PR TITLE
android-system-image: use latest image built on jenkins

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
@Tofee @Herrie82

**Review by Tofee — APPROVED** [review]
Looks good, let's try.
Also, good idea to remove the redundant md5sum line.

**Comment by Herrie82** [comment]
@shr-project LGTM

**Review by Herrie82 — APPROVED** [review]

**Comment by shr-project** [comment]
6fcd9400..0cd461ac  hardknott -> hardknott
   6fcd9400..0cd461ac  master -> master

**Pull request merged**
